// Generated by scripts/tts_build.py from script/narration.txt.
export type SubEntry = {from: number; to: number; text: string};
export const SUBS: SubEntry[] = [
  {from: 25, to: 84, text: "Power Platform connects business apps,"},
  {from: 85, to: 142, text: "automation, websites, and agents."},
  {from: 149, to: 204, text: "Dataverse gives them shared tables,"},
  {from: 205, to: 254, text: "relationships, and security."},
  {from: 261, to: 346, text: "Develop an unmanaged solution in source control,"},
  {from: 347, to: 404, text: "then promote the same managed artifact"},
  {from: 405, to: 446, text: "through test and production."},
  {from: 453, to: 495, text: "Configure each environment's"},
  {from: 496, to: 547, text: "connections and variables;"},
  {from: 548, to: 608, text: "migrate table records separately."},
  {from: 615, to: 698, text: "Use Power Platform pipelines, GitHub Actions,"},
  {from: 699, to: 748, text: "or Azure DevOps Build Tools"},
  {from: 749, to: 785, text: "to automate delivery."},
  {from: 792, to: 851, text: "Before release, check connector policies,"},
  {from: 852, to: 909, text: "tests, monitoring, licensing,"},
  {from: 910, to: 947, text: "and feature availability."},
  {from: 954, to: 1007, text: "Low code makes delivery faster,"},
  {from: 1008, to: 1048, text: "not governance optional."},
];
