// Generated by scripts/sync_scenes.py.
export const SCENES = [
  {
    "id": "SC01",
    "from": 1,
    "to": 148,
    "label": "One platform"
  },
  {
    "id": "SC02",
    "from": 149,
    "to": 260,
    "label": "Shared foundation"
  },
  {
    "id": "SC03",
    "from": 261,
    "to": 452,
    "label": "Production delivery"
  },
  {
    "id": "SC04",
    "from": 453,
    "to": 614,
    "label": "Configuration and data"
  },
  {
    "id": "SC05",
    "from": 615,
    "to": 791,
    "label": "CI/CD"
  },
  {
    "id": "SC06",
    "from": 792,
    "to": 1090,
    "label": "Governed release"
  }
];
