// Generated by scripts/tts_build.py. Frames are 1-based and inclusive.
export const TOTAL_FRAMES = 1090;
export const CHAPTER_STARTS: Array<{n: number; title: string; from: number}> = [
  {n: 1, title: "One platform", from: 25},
  {n: 2, title: "Shared foundation", from: 149},
  {n: 3, title: "Production delivery", from: 261},
  {n: 4, title: "Configuration and data", from: 453},
  {n: 5, title: "CI/CD", from: 615},
  {n: 6, title: "Governed release", from: 792},
];
export type Sentence = {id: string; chapter: number; from: number; to: number; text: string};
export const SENTENCES: Sentence[] = [
  {id: "S01", chapter: 1, from: 25, to: 142, text: "Power Platform connects business apps, automation, websites, and agents."},
  {id: "S02", chapter: 2, from: 149, to: 254, text: "Dataverse gives them shared tables, relationships, and security."},
  {id: "S03", chapter: 3, from: 261, to: 446, text: "Develop an unmanaged solution in source control, then promote the same managed artifact through test and production."},
  {id: "S04", chapter: 4, from: 453, to: 608, text: "Configure each environment's connections and variables; migrate table records separately."},
  {id: "S05", chapter: 5, from: 615, to: 785, text: "Use Power Platform pipelines, GitHub Actions, or Azure DevOps Build Tools to automate delivery."},
  {id: "S06", chapter: 6, from: 792, to: 947, text: "Before release, check connector policies, tests, monitoring, licensing, and feature availability."},
  {id: "S07", chapter: 6, from: 954, to: 1048, text: "Low code makes delivery faster, not governance optional."},
];
