// Generated by scripts/tts_build.py from script/narration.txt.
export type SubEntry = {from: number; to: number; text: string};
export const SUBS: SubEntry[] = [
  {from: 31, to: 120, text: "Copilot is a family of AI experiences,"},
  {from: 121, to: 176, text: "not one interchangeable tool."},
  {from: 181, to: 263, text: "Copilot Chat helps people research and draft."},
  {from: 268, to: 367, text: "Microsoft 365 Copilot brings assistance"},
  {from: 368, to: 459, text: "into work apps and, with the right access,"},
  {from: 460, to: 507, text: "organizational information."},
  {from: 512, to: 567, text: "GitHub Copilot supports coding."},
  {from: 572, to: 645, text: "Copilot Studio helps teams build agents"},
  {from: 646, to: 720, text: "connected to their own knowledge and tools."},
  {from: 725, to: 759, text: "Choose by the job,"},
  {from: 760, to: 823, text: "then check permissions, licensing,"},
  {from: 824, to: 850, text: "and the output."},
];
