// Generated by scripts/tts_build.py. Frames are 1-based and inclusive.
export const TOTAL_FRAMES = 900;
export const CHAPTER_STARTS: Array<{n: number; title: string; from: number}> = [
  {n: 1, title: "Choose by the job", from: 31},
];
export type Sentence = {id: string; chapter: number; from: number; to: number; text: string};
export const SENTENCES: Sentence[] = [
  {id: "S01", chapter: 1, from: 31, to: 176, text: "Copilot is a family of AI experiences, not one interchangeable tool."},
  {id: "S02", chapter: 1, from: 181, to: 263, text: "Copilot Chat helps people research and draft."},
  {id: "S03", chapter: 1, from: 268, to: 507, text: "Microsoft 365 Copilot brings assistance into work apps and, with the right access, organizational information."},
  {id: "S04", chapter: 1, from: 512, to: 567, text: "GitHub Copilot supports coding."},
  {id: "S05", chapter: 1, from: 572, to: 720, text: "Copilot Studio helps teams build agents connected to their own knowledge and tools."},
  {id: "S06", chapter: 1, from: 725, to: 850, text: "Choose by the job, then check permissions, licensing, and the output."},
];
