// Generated by scripts/sapi_build.py from script/narration.txt.
export type SubEntry = {from: number; to: number; text: string};
export const SUBS: SubEntry[] = [
  {from: 25, to: 78, text: "Microsoft Copilot Studio has moved beyond"},
  {from: 79, to: 102, text: "the chatbot frame."},
  {from: 113, to: 163, text: "It is a low-code studio for building agents,"},
  {from: 164, to: 230, text: "workflows, and agent flows that connect to business data"},
  {from: 231, to: 276, text: "and publish where people already work."},
  {from: 287, to: 352, text: "With generative orchestration, an agent can choose"},
  {from: 353, to: 424, text: "the right topic, tool, knowledge source, or other agent,"},
  {from: 425, to: 492, text: "then ask for missing inputs and compose the response."},
  {from: 503, to: 598, text: "Tools turn intent into action: connectors, agent flows,"},
  {from: 599, to: 669, text: "prompts, REST APIs, MCP, and computer use"},
  {from: 670, to: 743, text: "for systems that still only expose a screen."},
  {from: 754, to: 842, text: "The enterprise story is control: data policies, audit,"},
  {from: 843, to: 918, text: "Agent 365 visibility, Entra agent identities,"},
  {from: 919, to: 992, text: "cost governance, and repeatable evaluations"},
  {from: 993, to: 1032, text: "before and after launch."},
  {from: 1043, to: 1113, text: "The executive takeaway: scale adaptive automation,"},
  {from: 1114, to: 1171, text: "but run it like a managed business platform."},
];
