// Generated by scripts/sapi_build.py. Frames are 1-based and inclusive.
export const TOTAL_FRAMES = 1216;
export const CHAPTER_STARTS: Array<{n: number; title: string; from: number}> = [
  {n: 1, title: "Managed agents", from: 25},
];
export type Sentence = {id: string; chapter: number; from: number; to: number; text: string};
export const SENTENCES: Sentence[] = [
  {id: "S01", chapter: 1, from: 25, to: 102, text: "Microsoft Copilot Studio has moved beyond the chatbot frame."},
  {id: "S02", chapter: 1, from: 113, to: 276, text: "It is a low-code studio for building agents, workflows, and agent flows that connect to business data and publish where people already work."},
  {id: "S03", chapter: 1, from: 287, to: 492, text: "With generative orchestration, an agent can choose the right topic, tool, knowledge source, or other agent, then ask for missing inputs and compose the response."},
  {id: "S04", chapter: 1, from: 503, to: 743, text: "Tools turn intent into action: connectors, agent flows, prompts, REST APIs, MCP, and computer use for systems that still only expose a screen."},
  {id: "S05", chapter: 1, from: 754, to: 1032, text: "The enterprise story is control: data policies, audit, Agent 365 visibility, Entra agent identities, cost governance, and repeatable evaluations before and after launch."},
  {id: "S06", chapter: 1, from: 1043, to: 1171, text: "The executive takeaway: scale adaptive automation, but run it like a managed business platform."},
];
