// Generated by scripts/tts_build.py from script/narration.txt.
export type SubEntry = {from: number; to: number; text: string};
export const SUBS: SubEntry[] = [
  {from: 31, to: 107, text: "Microsoft spans the computer on your desk"},
  {from: 108, to: 163, text: "and the services behind your work."},
  {from: 168, to: 229, text: "Windows runs the PC experience."},
  {from: 234, to: 331, text: "Microsoft 365 supports documents,"},
  {from: 332, to: 392, text: "communication, and collaboration."},
  {from: 397, to: 476, text: "Azure supplies cloud computing, storage,"},
  {from: 477, to: 545, text: "and AI services for applications."},
  {from: 550, to: 599, text: "Copilot adds AI assistance"},
  {from: 600, to: 655, text: "across selected workflows."},
  {from: 660, to: 708, text: "These are connected products,"},
  {from: 709, to: 783, text: "not a single system: what you can use depends"},
  {from: 784, to: 867, text: "on the product, configuration, and subscription."},
];
