// Generated by scripts/tts_build.py. Frames are 1-based and inclusive.
export const TOTAL_FRAMES = 900;
export const CHAPTER_STARTS: Array<{n: number; title: string; from: number}> = [
  {n: 1, title: "Software to cloud", from: 31},
];
export type Sentence = {id: string; chapter: number; from: number; to: number; text: string};
export const SENTENCES: Sentence[] = [
  {id: "S01", chapter: 1, from: 31, to: 163, text: "Microsoft spans the computer on your desk and the services behind your work."},
  {id: "S02", chapter: 1, from: 168, to: 229, text: "Windows runs the PC experience."},
  {id: "S03", chapter: 1, from: 234, to: 392, text: "Microsoft 365 supports documents, communication, and collaboration."},
  {id: "S04", chapter: 1, from: 397, to: 545, text: "Azure supplies cloud computing, storage, and AI services for applications."},
  {id: "S05", chapter: 1, from: 550, to: 655, text: "Copilot adds AI assistance across selected workflows."},
  {id: "S06", chapter: 1, from: 660, to: 867, text: "These are connected products, not a single system: what you can use depends on the product, configuration, and subscription."},
];
