import { cpSync, createReadStream, existsSync, readFileSync, symlinkSync, unlinkSync } from 'node:fs';
import { readFile } from 'node:fs/promises';
import { spawnSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { digest, sha256 } from './canonical.ts';
import type { ContentIR, RenderSpec } from './contracts.ts';
import type { AdapterFile, AdapterRenderOptions } from './adapters.ts';

type SupportedImageMediaType = 'image/png' | 'image/jpeg';

interface ResolvedAsset {
  asset: ContentIR['assets'][number];
  mediaType?: SupportedImageMediaType;
  bytes?: Buffer;
  filename?: string;
}

const REMOTION_MP4_ADAPTER = 'a2swe-remotion-mp4-adapter-3';
export const MP4_ADAPTER = REMOTION_MP4_ADAPTER;
const REPOSITORY_ROOT = fileURLToPath(new URL('../../../', import.meta.url));
const REMOTION_ROOT_TEMPLATE = readFileSync(new URL('./remotion-root.template.txt', import.meta.url), 'utf8');
const REMOTION_PALETTE_TEMPLATE = readFileSync(new URL('./remotion-palette.template.txt', import.meta.url), 'utf8');
const REMOTION_VISUALS_TEMPLATE = readFileSync(new URL('./remotion-visuals.template.txt', import.meta.url), 'utf8');
const REMOTION_VISUALS_STUB = `export type Visual = { kind: 'mermaid' | 'excalidraw' | 'marp'; source: string; caption: string };

export function VisualPanel(_props: { visual: Visual; id: string; width: number; height: number; frame: number; settled?: boolean }) {
  return null;
}
`;
const VISUAL_DEPENDENCIES = { mermaid: '12.0.0', '@excalidraw/excalidraw': '0.18.1', '@marp-team/marp-core': '4.4.0' };
const VISUAL_EXTENSIONS = { mermaid: 'mmd', excalidraw: 'excalidraw.json', marp: 'marp.md' } as const;
type SectionVisual = NonNullable<ContentIR['sections'][number]['visual']>;

// Section identifiers may contain path separators, so files and compositions use an ordered, filesystem-safe stem.
export function visualStem(content: ContentIR, sectionId: string): string {
  const index = content.sections.findIndex((section) => section.sectionId === sectionId);
  return `${String(index + 1).padStart(2, '0')}-${slug(sectionId)}`;
}
const TEMPLATE_REQUIREMENTS_LOCK = readFileSync(new URL('../../../template/requirements.lock.txt', import.meta.url), 'utf8');
const GENERATED_REQUIREMENTS_LOCK = Buffer.from(TEMPLATE_REQUIREMENTS_LOCK.replace(
  /^# This file was autogenerated by uv via the following command:\r?\n#    .*?\r?\n/,
  '# This file is emitted by the a2swe media adapter from the repository speech lock.\n# Direct URLs are used for installed-package provenance checks; no runtime installer is invoked.\n'
));

function stableJson(value: unknown): Buffer {
  return Buffer.from(`${JSON.stringify(value, null, 2)}\n`);
}

function slug(value: string): string {
  return value.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '').slice(0, 80) || 'item';
}

function imageExtension(mediaType: SupportedImageMediaType): 'png' | 'jpg' {
  return mediaType === 'image/png' ? 'png' : 'jpg';
}

function assetExtension(mediaType: string): string {
  if (mediaType === 'image/png') return '.png';
  if (mediaType === 'image/jpeg') return '.jpg';
  if (mediaType === 'image/svg+xml') return '.svg';
  if (mediaType === 'video/mp4') return '.mp4';
  return '.asset';
}

function assertSupportedImageBytes(mediaType: SupportedImageMediaType, bytes: Buffer, assetId: string): void {
  const png = bytes.subarray(0, 8).equals(Buffer.from([137, 80, 78, 71, 13, 10, 26, 10]));
  const jpeg = bytes[0] === 255 && bytes[1] === 216 && bytes[2] === 255;
  if ((mediaType === 'image/png' && !png) || (mediaType === 'image/jpeg' && !jpeg)) throw new Error(`asset_embed_invalid_raster: ${assetId}`);
}

function resolveAssetEmbeds(content: ContentIR, options: AdapterRenderOptions): Map<string, ResolvedAsset> {
  const resolved: Map<string, ResolvedAsset> = new Map(content.assets.map((asset) => [asset.assetId, { asset }]));
  const seen = new Set<string>();
  for (const embed of options.assetEmbeds ?? []) {
    const current = resolved.get(embed.assetId);
    if (!current) throw new Error(`unknown_asset_embed: ${embed.assetId}`);
    if (seen.has(embed.assetId)) throw new Error(`duplicate_asset_embed: ${embed.assetId}`);
    seen.add(embed.assetId);
    if (embed.mediaType !== 'image/png' && embed.mediaType !== 'image/jpeg') throw new Error(`unsupported_asset_embed_media_type: ${embed.assetId}`);
    if (current.asset.mediaType !== embed.mediaType) throw new Error(`asset_embed_media_type_mismatch: ${embed.assetId}`);
    assertSupportedImageBytes(embed.mediaType, embed.bytes, embed.assetId);
    if (sha256(embed.bytes) !== current.asset.digest) throw new Error(`asset_embed_digest_mismatch: ${embed.assetId}`);
    resolved.set(embed.assetId, {
      asset: current.asset,
      mediaType: embed.mediaType,
      bytes: embed.bytes,
      filename: `${slug(embed.assetId)}-${current.asset.digest.slice(0, 12)}.${imageExtension(embed.mediaType)}`
    });
  }
  return resolved;
}

function citationFor(content: ContentIR, evidenceId: string): ContentIR['citations'][number] {
  const citation = content.citations.find((item) => item.evidenceId === evidenceId);
  if (!citation) throw new Error('missing_citation');
  return citation;
}

function citationLabel(content: ContentIR, evidenceId: string): string {
  return '[' + evidenceId + '] ' + citationFor(content, evidenceId).sourceTitle;
}

function claimFor(content: ContentIR, claimId: string): ContentIR['claims'][number] {
  const claim = content.claims.find((item) => item.claimId === claimId);
  if (!claim) throw new Error('missing_claim');
  return claim;
}

function digestBoundNarration(content: ContentIR, spec: RenderSpec, timeline: ReturnType<typeof remotionTimeline>): unknown {
  return {
    schemaVersion: '1.0.0',
    contentId: content.contentId,
    contentDigest: digest(content),
    text: content.voice.narration,
    segments: content.voice.narration.split(/\r?\n[ \t]*\r?\n/).map((part) => part.trim()).filter(Boolean),
    narrationSha256: sha256(Buffer.from(content.voice.narration, 'utf8')),
    language: content.language,
    externalTransfer: content.voice.externalTransfer,
    outputWav: `public/assets/${content.contentId}/audio.wav`,
    metadataPath: 'audio/narration-metadata.json',
    sampleRate: spec.video.sampleRate,
    channels: 2,
    expectedDurationSeconds: timeline.durationInFrames / timeline.fps,
    maxDurationDriftSeconds: 2 / timeline.fps,
    allowedEngines: ['kokoro', 'kokoro_onnx'],
    modelPathContract: {
      kokoro: ['A2SWE_KOKORO_CONFIG', 'A2SWE_KOKORO_WEIGHTS', 'A2SWE_KOKORO_VOICE_MODEL'],
      kokoro_onnx: ['KOKORO_ONNX_MODEL', 'KOKORO_ONNX_VOICES']
    }
  };
}

function remotionAssetManifest(content: ContentIR, spec: RenderSpec, assetMap: Map<string, ResolvedAsset>, timeline: ReturnType<typeof remotionTimeline>): unknown {
  return {
    schemaVersion: '1.0.0',
    contentDigest: digest(content),
    audio: {
      required: true,
      path: `public/assets/${content.contentId}/audio.wav`,
      metadataPath: 'audio/narration-metadata.json',
      narrationManifestPath: 'speech/narration-manifest.json',
      narrationSha256: sha256(Buffer.from(content.voice.narration, 'utf8')),
      expectedDurationSeconds: timeline.durationInFrames / timeline.fps,
      maxDurationDriftSeconds: 2 / timeline.fps,
      sampleRate: spec.video.sampleRate,
      source: 'Generated locally from digest-bound narration via Python 3.14 Kokoro ONNX or optional Kokoro/Misaki using configured local model paths.',
      digestBoundInContentIR: true,
      command: 'npm run audio'
    },
    assets: content.assets.map((asset) => {
      const resolved = assetMap.get(asset.assetId);
      const filename = resolved?.filename ?? `${asset.assetId}${assetExtension(asset.mediaType)}`;
      return {
        assetId: asset.assetId,
        role: asset.role,
        mediaType: asset.mediaType,
        alt: asset.alt,
        digest: asset.digest,
        path: `public/assets/${content.contentId}/${filename}`,
        availableInPackage: Boolean(resolved?.bytes),
        requiredForRender: true
      };
    })
  };
}

function remotionTimeline(content: ContentIR, spec: RenderSpec): { schemaVersion: string; fps: number; width: number; height: number; sampleRate: number; durationInFrames: number; scenes: { id: string; kind: string; title: string; body: string; narration: string; speechStartFrame: number; speechEndFrame: number; decision: string; claims: string[]; claimSources: string[]; citations: { evidenceId: string; sourceTitle: string; canonicalUrl: string }[]; assetIds: string[]; visual: SectionVisual | null; visualId: string | null; startFrame: number; durationInFrames: number; endFrame: number }[] } {
  const durationInFrames = Math.max(1, Math.ceil(spec.video.durationSeconds * spec.video.fps));
  const sceneInputs = [
    {
      id: 'title',
      kind: 'title',
      title: content.title,
      body: content.summary,
      narration: content.summary,
      claims: content.claims.map((claim) => claim.text),
      claimSources: content.claims.map((claim) => citationLabel(content, claim.evidenceIds[0])),
      citations: content.citations,
      assetIds: content.assets.map((asset) => asset.assetId),
      visual: null as SectionVisual | null,
      visualId: null as string | null
    },
    ...content.sections.map((section) => {
      const claims = section.claimIds.map((id) => claimFor(content, id));
      const evidenceIds = [...new Set(claims.flatMap((claim) => claim.evidenceIds))];
      return {
        id: section.sectionId,
        kind: 'section',
        title: section.title,
        body: section.body,
        narration: section.body,
        claims: claims.map((claim) => claim.text),
        claimSources: claims.map((claim) => citationLabel(content, claim.evidenceIds[0])),
        citations: evidenceIds.map((id) => citationFor(content, id)),
        assetIds: section.assetIds,
        visual: section.visual ?? null,
        visualId: section.visual ? visualStem(content, section.sectionId) : null
      };
    })
  ];
  if (durationInFrames < sceneInputs.length) {
    throw new Error(`remotion_timeline_too_short: ${durationInFrames} frames cannot show ${sceneInputs.length} scenes`);
  }
  const base = Math.floor(durationInFrames / sceneInputs.length);
  const remainder = durationInFrames % sceneInputs.length;
  let startFrame = 0;
  const scenes = sceneInputs.map((scene, index) => {
    const sceneDuration = base + (index < remainder ? 1 : 0);
    const output = {
      ...scene,
      decision: content.decision,
      citations: scene.citations.map((citation) => ({
        evidenceId: citation.evidenceId,
        sourceTitle: citation.sourceTitle,
        canonicalUrl: citation.canonicalUrl
      })),
      startFrame,
      durationInFrames: sceneDuration,
      endFrame: startFrame + sceneDuration,
      speechStartFrame: startFrame,
      speechEndFrame: startFrame + sceneDuration
    };
    startFrame += sceneDuration;
    return output;
  });
  return { schemaVersion: '1.0.0', fps: spec.video.fps, width: spec.video.width, height: spec.video.height, sampleRate: spec.video.sampleRate, durationInFrames, scenes };
}

function synthesizeAudioWrapperScript(): string {
  return `import { existsSync } from 'node:fs';
import { dirname, isAbsolute, join, resolve } from 'node:path';
import { spawnSync } from 'node:child_process';

const root = process.cwd();
let python = process.env.A2SWE_PYTHON;
if (python && !isAbsolute(python)) {
  throw new Error('A2SWE_MP4_AUDIO_FAILED: A2SWE_PYTHON must be an absolute Python 3.14 interpreter path');
}
if (!python) {
  for (let dir = root; ; dir = dirname(dir)) {
    const candidate = join(dir, '.venv', process.platform === 'win32' ? 'Scripts' : 'bin', process.platform === 'win32' ? 'python.exe' : 'python');
    if (existsSync(candidate)) { python = candidate; break; }
    if (dirname(dir) === dir) break;
  }
}
if (!python || !existsSync(python)) {
  throw new Error('A2SWE_MP4_AUDIO_FAILED: create a Python 3.14 .venv with requirements.lock.txt installed, or set absolute A2SWE_PYTHON');
}
const version = spawnSync(python, ['-c', 'import sys; print(sys.version.split()[0]); sys.exit(sys.version_info[:2] != (3, 14))'], { cwd: root, encoding: 'utf8', windowsHide: true });
if (version.error) throw new Error(\`A2SWE_MP4_AUDIO_FAILED: Python version check failed: \${version.error.message}\`);
if (version.status !== 0) {
  throw new Error(\`A2SWE_MP4_AUDIO_FAILED: Python 3.14 required; got \${version.stdout.trim() || version.stderr.trim() || 'unknown'}\`);
}
const result = spawnSync(python, [resolve(root, 'scripts/synthesize-audio.py'), 'speech/narration-manifest.json'], {
  cwd: root,
  stdio: 'inherit',
  env: { ...process.env, PYTHONUTF8: '1' },
  windowsHide: true
});
if (result.error) throw new Error(\`A2SWE_MP4_AUDIO_FAILED: local Kokoro synthesis failed to start: \${result.error.message}\`);
process.exit(result.status ?? 1);
`;
}

function synthesizeAudioPython(): string {
  return `#!/usr/bin/env python3
"""Core-managed local Kokoro/Kokoro-ONNX narration for the generated MP4 adapter."""
from __future__ import annotations

import hashlib
import json
import math
import os
import re
import sys
import tempfile
import wave
from importlib.metadata import PackageNotFoundError, distribution
from pathlib import Path
from urllib.parse import unquote, urldefrag, urlparse

REQUIRED_PYTHON = (3, 14)
KOKORO_REPO = 'hexgrad/Kokoro-82M'
OFFLINE_ENV = {
    'HF_HUB_OFFLINE': '1',
    'TRANSFORMERS_OFFLINE': '1',
    'HF_DATASETS_OFFLINE': '1',
    'HF_HUB_DISABLE_TELEMETRY': '1',
}


def fail(message: str) -> None:
    raise SystemExit(f'A2SWE_MP4_AUDIO_FAILED: {message}')


def sha256_path(path: Path) -> str:
    with path.open('rb') as stream:
        return hashlib.file_digest(stream, 'sha256').hexdigest()


def sha256_text(value: str) -> str:
    return hashlib.sha256(value.encode('utf-8')).hexdigest()


def write_json_atomic(path: Path, value: object) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile(mode='w', encoding='utf-8', dir=path.parent, suffix='.tmp', delete=False) as stream:
        temporary = Path(stream.name)
        json.dump(value, stream, indent=2, sort_keys=True)
        stream.write('\\n')
    try:
        os.replace(temporary, path)
    finally:
        temporary.unlink(missing_ok=True)


def require_python314() -> None:
    if sys.version_info[:2] != REQUIRED_PYTHON:
        fail(f'Python {REQUIRED_PYTHON[0]}.{REQUIRED_PYTHON[1]} is required; got {sys.version.split()[0]}')


def require_file_env(name: str, suffixes: tuple[str, ...] = ()) -> Path:
    value = os.environ.get(name, '')
    if not value:
        fail(f'{name} must point to a local model file')
    path = Path(value)
    if not path.is_absolute():
        fail(f'{name} must be an absolute path: {value}')
    if not path.is_file():
        fail(f'{name} does not exist or is not a file: {path}')
    if suffixes and path.suffix.lower() not in suffixes:
        fail(f'{name} must use one of these file extensions: {", ".join(suffixes)}')
    return path


def enforce_offline_runtime() -> None:
    os.environ.update(OFFLINE_ENV)
    import socket

    def blocked_connect(*_args, **_kwargs):
        raise OSError('A2SWE_MP4_AUDIO_FAILED: network access is disabled for local MP4 speech synthesis')

    socket.create_connection = blocked_connect
    socket.socket.connect = blocked_connect
    socket.socket.connect_ex = blocked_connect


def validate_lock_references(root: Path, lock: str) -> None:
    project_root = root.resolve()
    for line in lock.splitlines():
        match = re.search(r'^\\S+(?:\\[.*?\\])? @ (\\S+)$', line)
        if not match:
            continue
        reference = urldefrag(match.group(1))[0]
        parsed = urlparse(reference)
        if parsed.scheme in ('http', 'https'):
            continue
        if parsed.scheme == 'file':
            raw_path = unquote(parsed.path)
            if os.name == 'nt' and re.match(r'^/[A-Za-z]:/', raw_path):
                raw_path = raw_path[1:]
            path = Path(raw_path)
        elif parsed.scheme:
            fail(f'requirements.lock.txt contains unsupported direct reference scheme: {parsed.scheme}')
        else:
            path = Path(unquote(reference))
            if not path.is_absolute():
                path = root / path
        resolved = path.resolve()
        try:
            resolved.relative_to(project_root)
        except ValueError:
            fail(f'requirements.lock.txt local path reference must stay inside the generated project: {reference}')
        if not resolved.exists():
            fail(f'requirements.lock.txt local path reference is missing inside the generated project: {reference}')


def verify_lock_source(root: Path, engine: str) -> dict[str, object]:
    names = {'kokoro': ('kokoro', 'misaki'), 'kokoro_onnx': ('kokoro-onnx',)}[engine]
    lock_path = root / 'requirements.lock.txt'
    if not lock_path.is_file():
        fail('requirements.lock.txt is required for speech provenance')
    lock = lock_path.read_text(encoding='utf-8')
    validate_lock_references(root, lock)
    result: dict[str, object] = {}
    for name in names:
        match = re.search(rf'^{re.escape(name)}(?:\\[.*?\\])? @ (\\S+)$', lock, re.MULTILINE)
        if not match:
            fail(f'Missing pinned {name} wheel in requirements.lock.txt')
        expected, fragment = urldefrag(match.group(1))
        if not re.fullmatch(r'sha256=[0-9a-f]{64}', fragment):
            fail(f'{name} wheel must be pinned by SHA-256')
        try:
            package = distribution(name)
        except PackageNotFoundError:
            fail(f'{name} is not installed in the selected Python 3.14 environment')
        source = json.loads(package.read_text('direct_url.json') or '{}')
        if unquote(source.get('url', '')) != unquote(expected):
            fail(f'{name} is not the locked fork build; install requirements.lock.txt')
        result[name] = {
            'version': package.version,
            'url': expected,
            'locked_wheel_sha256': fragment.removeprefix('sha256='),
            'installed_source': source,
        }
    return result


def import_audio_deps():
    try:
        import numpy as np
        import soundfile as sf
        from scipy.signal import resample_poly
    except ImportError as exc:
        fail(f'missing required audio dependency from requirements.lock.txt: {exc.name}')
    return np, sf, resample_poly


def validate_narration(payload: dict[str, object]) -> str:
    if payload.get('schemaVersion') != '1.0.0':
        fail('narration schemaVersion must be 1.0.0')
    if payload.get('language') != 'en':
        fail('only English narration is supported by the local speech stack')
    if payload.get('externalTransfer') is not False:
        fail('narration must not permit external speech transfer')
    text = payload.get('text')
    if not isinstance(text, str) or not text.strip():
        fail('narration text must be a nonempty string')
    if re.search(r'[\\u3400-\\u9fff]', text):
        fail('English-only narration is required')
    expected_digest = payload.get('narrationSha256')
    if expected_digest != sha256_text(text):
        fail('narration digest does not match text')
    return text


def resolve_engine() -> str:
    requested = os.environ.get('A2SWE_TTS_ENGINE') or os.environ.get('TTS_ENGINE') or 'auto'
    if requested not in ('auto', 'kokoro', 'kokoro_onnx'):
        fail('A2SWE_TTS_ENGINE/TTS_ENGINE must be auto, kokoro, or kokoro_onnx')
    if requested != 'auto':
        return requested
    full_kokoro = all(os.environ.get(name) for name in ('A2SWE_KOKORO_CONFIG', 'A2SWE_KOKORO_WEIGHTS', 'A2SWE_KOKORO_VOICE_MODEL'))
    onnx = all(os.environ.get(name) for name in ('KOKORO_ONNX_MODEL', 'KOKORO_ONNX_VOICES'))
    if onnx:
        return 'kokoro_onnx'
    if full_kokoro:
        return 'kokoro'
    fail('auto speech requires configured local model paths: A2SWE_KOKORO_CONFIG/A2SWE_KOKORO_WEIGHTS/A2SWE_KOKORO_VOICE_MODEL or KOKORO_ONNX_MODEL/KOKORO_ONNX_VOICES')


def synth_kokoro(segments: list[str]):
    enforce_offline_runtime()
    np, _, _ = import_audio_deps()
    try:
        from kokoro import KModel, KPipeline
    except ImportError:
        fail('TTS_ENGINE=kokoro requires locked kokoro and misaki fork wheels')
    config = require_file_env('A2SWE_KOKORO_CONFIG', ('.json',))
    weights = require_file_env('A2SWE_KOKORO_WEIGHTS', ('.pth',))
    voice_model = require_file_env('A2SWE_KOKORO_VOICE_MODEL', ('.pt',))
    lang = os.environ.get('KOKORO_LANG', 'a')
    speed = float(os.environ.get('KOKORO_SPEED', '1.0'))
    if not math.isfinite(speed) or speed <= 0:
        fail('KOKORO_SPEED must be a positive finite number')
    model = KModel(repo_id=KOKORO_REPO, config=str(config), model=str(weights)).eval()
    pipeline = KPipeline(lang_code=lang, repo_id=KOKORO_REPO, model=model)
    pieces = []
    token_count = 0
    for segment in segments:
        parts = []
        for result in pipeline(segment, voice=str(voice_model), speed=speed):
            if result.audio is None or not result.tokens:
                fail('Kokoro must return audio and English token timestamps')
            parts.append(result.audio.detach().cpu().numpy().reshape(-1))
            token_count += len(result.tokens)
        if not parts:
            fail('Kokoro returned no audio')
        pieces.append(np.concatenate(parts))
    return pieces, 24000, {'voice': str(voice_model), 'lang': lang, 'speed': speed, 'tokens': token_count}


def synth_kokoro_onnx(segments: list[str]):
    enforce_offline_runtime()
    np, _, _ = import_audio_deps()
    try:
        from kokoro_onnx import Kokoro
    except ImportError:
        fail('TTS_ENGINE=kokoro_onnx requires the locked kokoro-onnx fork wheel')
    model = require_file_env('KOKORO_ONNX_MODEL', ('.onnx',))
    voices = require_file_env('KOKORO_ONNX_VOICES')
    voice = os.environ.get('KOKORO_ONNX_VOICE', 'am_michael')
    lang = os.environ.get('KOKORO_ONNX_LANG', 'en-us')
    speed = float(os.environ.get('KOKORO_SPEED', '1.0'))
    if not math.isfinite(speed) or speed <= 0:
        fail('KOKORO_SPEED must be a positive finite number')
    kokoro = Kokoro(str(model), str(voices))
    pieces = []
    sample_rate = 24000
    for segment in segments:
        samples, sample_rate = kokoro.create(segment, voice=voice, speed=speed, lang=lang)
        pieces.append(np.asarray(samples, dtype=np.float32).reshape(-1))
    return pieces, int(sample_rate), {'voice': voice, 'lang': lang, 'speed': speed}


def assemble_segments(pieces, sample_rate: int, segments: list[str]):
    np, _, _ = import_audio_deps()
    lead, gap, tail = 0.25, 0.55, 0.5
    cursor = int(lead * sample_rate)
    chunks = [np.zeros(cursor, dtype=np.float32)]
    timings = []
    for index, (piece, text) in enumerate(zip(pieces, segments)):
        if piece.size == 0:
            fail('speech engine returned an empty segment')
        chunks.append(piece)
        timings.append({'index': index, 'text': text, 'startSeconds': cursor / sample_rate, 'endSeconds': (cursor + piece.size) / sample_rate})
        cursor += piece.size
        spacer = int((gap if index < len(pieces) - 1 else tail) * sample_rate)
        chunks.append(np.zeros(spacer, dtype=np.float32))
        cursor += spacer
    return np.concatenate(chunks), timings


def resample_to_target(audio, sample_rate: int, target_rate: int):
    np, _, resample_poly = import_audio_deps()
    if sample_rate == target_rate:
        return np.asarray(audio, dtype=np.float32)
    divisor = math.gcd(sample_rate, target_rate)
    return np.asarray(resample_poly(audio, target_rate // divisor, sample_rate // divisor), dtype=np.float32)


def write_wav(path: Path, audio, sample_rate: int, channels: int) -> None:
    np, _, _ = import_audio_deps()
    array = np.asarray(audio, dtype=np.float32)
    if array.ndim != 1 or array.size == 0:
        fail('speech engine returned empty or non-mono audio')
    if not np.isfinite(array).all():
        fail('speech engine returned non-finite audio samples')
    if not np.any(array):
        fail('speech engine returned entirely silent audio')
    peak = float(np.max(np.abs(array))) or 1.0
    array = array / peak * 0.89
    if channels == 2:
        array = np.stack([array, array], axis=1)
    elif channels != 1:
        fail(f'unsupported WAV channel count: {channels}')
    pcm = (np.clip(array, -1.0, 1.0) * 32767).astype(np.int16)
    path.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile(dir=path.parent, suffix='.wav', delete=False) as stream:
        temporary = Path(stream.name)
    try:
        with wave.open(str(temporary), 'wb') as output:
            output.setnchannels(channels)
            output.setsampwidth(2)
            output.setframerate(sample_rate)
            output.writeframes(pcm.tobytes())
        os.replace(temporary, path)
    finally:
        temporary.unlink(missing_ok=True)


def probe_duration(path: Path) -> float:
    with wave.open(str(path), 'rb') as wav:
        frames = wav.getnframes()
        sample_rate = wav.getframerate()
        if sample_rate <= 0 or frames <= 0:
            fail(f'generated WAV has invalid duration metadata: {path}')
        return frames / sample_rate


def main() -> None:
    require_python314()
    root = Path(__file__).resolve().parents[1]
    manifest_path = root / (sys.argv[1] if len(sys.argv) > 1 else 'speech/narration-manifest.json')
    payload = json.loads(manifest_path.read_text(encoding='utf-8'))
    text = validate_narration(payload)
    if int(payload.get('sampleRate', 0)) != 48000:
        fail('narration sampleRate must be 48000')
    if int(payload.get('channels', 0)) != 2:
        fail('narration channels must be 2')
    engine = resolve_engine()
    forks = verify_lock_source(root, engine)
    segments = payload.get('segments')
    if not isinstance(segments, list) or not segments or not all(isinstance(part, str) and part.strip() for part in segments):
        fail('narration segments must be a nonempty list of nonempty strings')
    if re.sub(r'\\s+', ' ', ' '.join(segments)).strip() != re.sub(r'\\s+', ' ', text).strip():
        fail('narration segments do not match narration text')
    if engine == 'kokoro':
        pieces, input_rate, voice_info = synth_kokoro(segments)
    else:
        pieces, input_rate, voice_info = synth_kokoro_onnx(segments)
    samples, timings = assemble_segments(pieces, input_rate, segments)
    output_rate = int(payload['sampleRate'])
    output_channels = int(payload['channels'])
    audio = resample_to_target(samples, input_rate, output_rate)
    output_wav = root / str(payload['outputWav'])
    write_wav(output_wav, audio, output_rate, output_channels)
    duration = probe_duration(output_wav)
    expected = float(payload['expectedDurationSeconds'])
    if not math.isfinite(expected) or expected <= 0:
        fail('requested narration duration must be positive and finite')
    model_files = {}
    if engine == 'kokoro':
        model_files = {name: {'path': str(require_file_env(env)), 'sha256': sha256_path(require_file_env(env))}
                       for name, env in {'config': 'A2SWE_KOKORO_CONFIG', 'weights': 'A2SWE_KOKORO_WEIGHTS', 'voice': 'A2SWE_KOKORO_VOICE_MODEL'}.items()}
    else:
        model_files = {name: {'path': str(require_file_env(env)), 'sha256': sha256_path(require_file_env(env))}
                       for name, env in {'weights': 'KOKORO_ONNX_MODEL', 'voices': 'KOKORO_ONNX_VOICES'}.items()}
    metadata = {
        'schemaVersion': '1.0.0',
        'engine': engine,
        'python': sys.version.split()[0],
        'interpreter': sys.executable,
        'contentDigest': payload['contentDigest'],
        'narrationSha256': payload['narrationSha256'],
        'audioFile': output_wav.relative_to(root).as_posix(),
        'audioSha256': sha256_path(output_wav),
        'sampleRate': output_rate,
        'channels': output_channels,
        'durationSeconds': duration,
        'requestedDurationSeconds': expected,
        'inputSampleRate': input_rate,
        'segments': timings,
        'voice': voice_info,
        'models': model_files,
        'forks': forks,
        'producer': Path(__file__).relative_to(root).as_posix(),
        'producerSha256': sha256_path(Path(__file__)),
        'requirementsLockSha256': sha256_path(root / 'requirements.lock.txt'),
    }
    write_json_atomic(root / str(payload['metadataPath']), metadata)
    print(json.dumps({'audio': metadata['audioFile'], 'sha256': metadata['audioSha256'], 'durationSeconds': duration, 'engine': engine}, sort_keys=True))


if __name__ == '__main__':
    main()
`;
}

function renderScript(): string {
  return `import { createHash } from 'node:crypto';
import { closeSync, existsSync, mkdirSync, openSync, readFileSync, readSync, statSync, unlinkSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { spawnSync } from 'node:child_process';

const root = process.cwd();
const readJson = (relative) => JSON.parse(readFileSync(path.join(root, relative), 'utf8'));
const plan = readJson('render-plan.json');
const content = readJson('src/content.json');
const timeline = readJson('timeline.json');
const manifest = readJson('asset-manifest.json');

function fail(message) {
  throw new Error(\`A2SWE_MP4_RENDER_FAILED: \${message}\`);
}

function run(command, args, label, options = {}) {
  const result = spawnSync(command, args, { cwd: root, encoding: 'utf8', maxBuffer: 16 * 1024 * 1024, windowsHide: true, ...options });
  if (result.error) fail(\`\${label} executable failed to start: \${result.error.message}\`);
  if (result.status !== 0) {
    const detail = (result.stderr || result.stdout || '').trim().slice(0, 4000);
    fail(\`\${label} exited with \${result.status}: \${detail}\`);
  }
  return result.stdout;
}

function requireFile(relative, label) {
  const absolute = path.join(root, relative);
  if (!existsSync(absolute) || !statSync(absolute).isFile()) fail(\`\${label} not found: \${relative}\`);
  if (statSync(absolute).size <= 0) fail(\`\${label} is empty: \${relative}\`);
  return absolute;
}

function sha256File(absolute) {
  const hash = createHash('sha256');
  const fd = openSync(absolute, 'r');
  const buffer = Buffer.allocUnsafe(1024 * 1024);
  try {
    let length;
    while ((length = readSync(fd, buffer, 0, buffer.length, null)) !== 0) hash.update(buffer.subarray(0, length));
  } finally {
    closeSync(fd);
  }
  return hash.digest('hex');
}

function readOptionalJson(relative) {
  const absolute = path.join(root, relative);
  if (!existsSync(absolute)) return undefined;
  return JSON.parse(readFileSync(absolute, 'utf8'));
}

function probeAudioDuration(ffprobe, audioPath) {
  const probe = JSON.parse(run(ffprobe, ['-v', 'error', '-show_streams', '-show_format', '-of', 'json', audioPath], 'ffprobe audio probe'));
  const audio = probe.streams?.find((stream) => stream.codec_type === 'audio');
  if (!audio) fail('narration WAV has no audio stream');
  if (Number(audio.sample_rate) !== timeline.sampleRate) fail(\`narration sample rate \${audio.sample_rate} does not match \${timeline.sampleRate}\`);
  const duration = Number(audio.duration ?? probe.format?.duration);
  if (!Number.isFinite(duration) || duration <= 0) fail('narration WAV duration is missing or invalid');
  return { audio, duration };
}

function audioMetadataValid(audioPath) {
  const metadata = readOptionalJson(manifest.audio.metadataPath);
  if (!metadata) return false;
  if (metadata.contentDigest !== plan.contentDigest) return false;
  if (metadata.narrationSha256 !== manifest.audio.narrationSha256) return false;
  if (metadata.audioFile !== manifest.audio.path) return false;
  if (metadata.audioSha256 !== sha256File(audioPath)) return false;
  if (Number(metadata.sampleRate) !== timeline.sampleRate) return false;
  if (Number(metadata.channels) !== 2) return false;
  if (!Number.isFinite(metadata.durationSeconds) || Number(metadata.durationSeconds) <= 0) return false;
  return true;
}

if (timeline.width !== 1920 || timeline.height !== 1080) fail(\`core MP4 adapter requires 1920x1080; got \${timeline.width}x\${timeline.height}\`);
if (timeline.fps !== 30) fail(\`core MP4 adapter requires 30fps; got \${timeline.fps}\`);
if (timeline.sampleRate !== 48000) fail(\`core MP4 adapter requires 48kHz audio; got \${timeline.sampleRate}\`);
requireFile('render-plan.json', 'render plan');
requireFile('src/content.json', 'ContentIR projection');
const remotion = requireFile('node_modules/@remotion/cli/remotion-cli.js', 'local Remotion CLI');
const tsc = requireFile('node_modules/typescript/bin/tsc', 'local TypeScript compiler');
const ffprobe = process.env.FFPROBE_PATH || 'ffprobe';
const ffmpeg = process.env.FFMPEG_PATH || 'ffmpeg';
run(ffprobe, ['-version'], 'ffprobe');
run(ffmpeg, ['-version'], 'ffmpeg');
requireFile(manifest.audio.narrationManifestPath, 'narration manifest');
if (!existsSync(path.join(root, manifest.audio.path)) || !audioMetadataValid(path.join(root, manifest.audio.path))) {
  run(process.execPath, ['scripts/synthesize-audio.mjs'], 'local Kokoro audio synthesis');
}
const audioPath = requireFile(manifest.audio.path, 'narration WAV');
if (!audioMetadataValid(audioPath)) fail('narration metadata does not match ContentIR narration, WAV digest, sample rate, channels, and duration');
const audioProbe = probeAudioDuration(ffprobe, audioPath);
const metadata = readJson(manifest.audio.metadataPath);
if (Math.abs(audioProbe.duration - Number(metadata.durationSeconds)) > 1 / timeline.sampleRate) fail('narration metadata duration does not match WAV');
const frames = Math.max(timeline.scenes.length, Math.ceil(audioProbe.duration * timeline.fps));
const segments = Array.isArray(metadata.segments) ? metadata.segments : [];
const aligned = segments.length === timeline.scenes.length;
const weights = timeline.scenes.map((scene) => Math.max(1, scene.title.length + scene.body.length));
const totalWeight = weights.reduce((sum, weight) => sum + weight, 0);
const cuts = [0];
timeline.scenes.forEach((scene, index) => {
  if (index === 0) return;
  const seconds = aligned ? (segments[index - 1].endSeconds + segments[index].startSeconds) / 2
    : audioProbe.duration * weights.slice(0, index).reduce((sum, weight) => sum + weight, 0) / totalWeight;
  cuts.push(Math.min(frames - (timeline.scenes.length - index), Math.max(cuts[index - 1] + 1, Math.round(seconds * timeline.fps))));
});
cuts.push(frames);
timeline.scenes.forEach((scene, index) => {
  const segment = aligned ? segments[index] : undefined;
  scene.startFrame = cuts[index];
  scene.endFrame = cuts[index + 1];
  scene.durationInFrames = scene.endFrame - scene.startFrame;
  scene.narration = segment ? segment.text : scene.narration;
  scene.speechStartFrame = segment ? Math.max(scene.startFrame, Math.round(segment.startSeconds * timeline.fps)) : scene.startFrame;
  scene.speechEndFrame = segment ? Math.min(scene.endFrame, Math.round(segment.endSeconds * timeline.fps)) : scene.startFrame - 1;
});
timeline.durationInFrames = frames;
plan.composition.durationInFrames = frames;
manifest.audio.expectedDurationSeconds = audioProbe.duration;
writeFileSync(path.join(root, 'timeline.json'), JSON.stringify(timeline, null, 2) + '\\n');
writeFileSync(path.join(root, 'render-plan.json'), JSON.stringify(plan, null, 2) + '\\n');
writeFileSync(path.join(root, 'asset-manifest.json'), JSON.stringify(manifest, null, 2) + '\\n');
for (const asset of manifest.assets) {
  const assetPath = requireFile(asset.path, \`asset \${asset.assetId}\`);
  const actual = sha256File(assetPath);
  if (actual !== asset.digest) fail(\`asset digest mismatch for \${asset.assetId}: expected \${asset.digest}, got \${actual}\`);
}
run(process.execPath, [tsc, '--noEmit'], 'TypeScript');
const output = path.join(root, plan.encodedMp4Path);
mkdirSync(path.dirname(output), { recursive: true });
if (existsSync(output) && process.env.A2SWE_OVERWRITE_MP4 !== '1') fail(\`refusing to overwrite existing MP4: \${plan.encodedMp4Path}\`);
const qcPath = path.join(root, 'qc', 'mp4-qc.json');
if (existsSync(qcPath)) unlinkSync(qcPath);
run(process.execPath, [remotion, 'render', 'src/index.tsx', content.contentId, plan.encodedMp4Path, '--codec=h264', '--crf=16', '--pixel-format=yuv420p', '--log=error'], 'Remotion render');
const outputHash = sha256File(output);
mkdirSync(path.join(root, 'qc'), { recursive: true });
writeFileSync(path.join(root, 'qc', 'render-receipt.json'), JSON.stringify({
  schemaVersion: '1.0.0',
  adapter: '${REMOTION_MP4_ADAPTER}',
  contentDigest: plan.contentDigest,
  output: plan.encodedMp4Path,
  outputSha256: outputHash,
  width: timeline.width,
  height: timeline.height,
  fps: timeline.fps,
  sampleRate: timeline.sampleRate,
  assets: manifest.assets.map((asset) => asset.assetId)
}, null, 2) + '\\n');
run(process.execPath, ['scripts/verify-mp4.mjs'], 'encoded MP4 QC');
console.log(JSON.stringify({ output: plan.encodedMp4Path, sha256: outputHash, adapter: '${REMOTION_MP4_ADAPTER}',
  qc: 'qc/mp4-qc.json', narrationDurationSeconds: audioProbe.duration }));
`;
}

function verifyScript(): string {
  return `import { createHash } from 'node:crypto';
import { closeSync, existsSync, mkdirSync, openSync, readFileSync, readSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { spawnSync } from 'node:child_process';

const root = process.cwd();
const plan = JSON.parse(readFileSync(path.join(root, 'render-plan.json'), 'utf8'));
const timeline = JSON.parse(readFileSync(path.join(root, 'timeline.json'), 'utf8'));
const manifest = JSON.parse(readFileSync(path.join(root, 'asset-manifest.json'), 'utf8'));
const ffprobe = process.env.FFPROBE_PATH || 'ffprobe';

function fail(message) {
  throw new Error(\`A2SWE_MP4_QC_FAILED: \${message}\`);
}

function run(command, args, label) {
  const result = spawnSync(command, args, { cwd: root, encoding: 'utf8', maxBuffer: 16 * 1024 * 1024, windowsHide: true });
  if (result.error) fail(\`\${label} executable failed to start: \${result.error.message}\`);
  if (result.status !== 0) fail(\`\${label} exited with \${result.status}: \${(result.stderr || result.stdout || '').trim().slice(0, 4000)}\`);
  return result.stdout;
}

function rate(value) {
  if (typeof value !== 'string') return 0;
  if (!value.includes('/')) return Number(value);
  const [num, den] = value.split('/').map(Number);
  return den ? num / den : 0;
}

function sha256File(absolute) {
  const hash = createHash('sha256');
  const fd = openSync(absolute, 'r');
  const buffer = Buffer.allocUnsafe(1024 * 1024);
  try {
    let length;
    while ((length = readSync(fd, buffer, 0, buffer.length, null)) !== 0) hash.update(buffer.subarray(0, length));
  } finally {
    closeSync(fd);
  }
  return hash.digest('hex');
}

const movie = path.join(root, plan.encodedMp4Path);
if (!existsSync(movie)) fail(\`MP4 not found: \${plan.encodedMp4Path}\`);
const receiptPath = path.join(root, 'qc', 'render-receipt.json');
if (!existsSync(receiptPath)) fail('render receipt is missing');
const receipt = JSON.parse(readFileSync(receiptPath, 'utf8'));
const outputSha256 = sha256File(movie);
if (receipt.output !== plan.encodedMp4Path || receipt.outputSha256 !== outputSha256 || receipt.contentDigest !== plan.contentDigest) {
  fail('encoded MP4 does not match its render receipt');
}
const probe = JSON.parse(run(ffprobe, ['-v', 'error', '-count_frames', '-show_streams', '-show_format', '-of', 'json', movie], 'ffprobe'));
const video = probe.streams?.find((stream) => stream.codec_type === 'video');
const audio = probe.streams?.find((stream) => stream.codec_type === 'audio');
if (!video) fail('MP4 has no video stream');
if (!audio) fail('MP4 has no audio stream');
if (video.codec_name !== 'h264') fail(\`expected H.264 video, got \${video.codec_name}\`);
if (Number(video.width) !== timeline.width || Number(video.height) !== timeline.height) fail(\`expected \${timeline.width}x\${timeline.height}, got \${video.width}x\${video.height}\`);
if (Math.abs(rate(video.r_frame_rate) - timeline.fps) > 0.001) fail(\`expected \${timeline.fps}fps, got \${video.r_frame_rate}\`);
if (video.pix_fmt !== 'yuv420p') fail(\`expected yuv420p pixel format, got \${video.pix_fmt}\`);
if (Number(video.nb_read_frames) !== timeline.durationInFrames) fail(\`expected \${timeline.durationInFrames} decoded video frames, got \${video.nb_read_frames}\`);
if (audio.codec_name !== 'aac') fail(\`expected AAC audio, got \${audio.codec_name}\`);
if (Number(audio.sample_rate) !== timeline.sampleRate) fail(\`expected \${timeline.sampleRate}Hz audio, got \${audio.sample_rate}\`);
if (Number(audio.channels) !== 2) fail(\`expected stereo audio, got \${audio.channels} channels\`);
const duration = Number(audio.duration ?? probe.format?.duration);
const expectedDuration = Number(manifest.audio.expectedDurationSeconds);
const durationTolerance = Number(manifest.audio.maxDurationDriftSeconds);
const videoDuration = timeline.durationInFrames / timeline.fps;
const aacPadding = 3 * 1024 / timeline.sampleRate;
if (!Number.isFinite(duration) || duration < expectedDuration - durationTolerance || duration > Math.max(expectedDuration + durationTolerance, videoDuration + aacPadding)) {
  fail(\`expected narration duration \${expectedDuration}s through video duration \${videoDuration}s plus AAC padding \${aacPadding}s, got \${duration}s\`);
}
const report = { schemaVersion: '1.0.0', adapter: '${REMOTION_MP4_ADAPTER}', file: plan.encodedMp4Path,
  contentDigest: plan.contentDigest, outputSha256, video, audio, container: probe.format };
if (!process.argv.includes('--verify-only')) {
  mkdirSync(path.join(root, 'qc'), { recursive: true });
  writeFileSync(path.join(root, 'qc', 'mp4-qc.json'), JSON.stringify(report, null, 2) + '\\n');
}
console.log(JSON.stringify({ valid: true, output: plan.encodedMp4Path, adapter: '${REMOTION_MP4_ADAPTER}' }));
`;
}

export function remotion(content: ContentIR, spec: RenderSpec, options: AdapterRenderOptions): AdapterFile[] {
  const timeline = remotionTimeline(content, spec);
  const renderOutput = 'dist/render.mp4';
  const assetMap = resolveAssetEmbeds(content, options);
  const narrationManifest = digestBoundNarration(content, spec, timeline);
  const assetManifest = remotionAssetManifest(content, spec, assetMap, timeline);
  const plan = {
    schemaVersion: '1.0.0',
    contentDigest: digest(content),
    renderer: 'remotion',
    encodedMp4: 'core-managed-on-render',
    encodedMp4Path: renderOutput,
    dependencyMode: 'local-only; no automatic package install, model download, or cloud speech fallback; Python 3.14 local Kokoro/Kokoro-ONNX model paths required',
    reason: 'Core invokes this 1080p Remotion MP4 project during production. The renderer synthesizes digest-bound narration with local Python 3.14 Kokoro ONNX (or explicit Kokoro/Misaki), measures the resulting WAV, derives scene frames, encodes MP4, and requires encoded-media QC.',
    composition: { id: content.contentId, width: spec.video.width, height: spec.video.height, fps: spec.video.fps, durationInFrames: timeline.durationInFrames, sampleRate: spec.video.sampleRate },
    paths: {
      entryPoint: 'src/index.tsx',
      rootComponent: 'src/Root.tsx',
      content: 'src/content.json',
      timeline: 'timeline.json',
      assetManifest: 'asset-manifest.json',
      audio: `public/assets/${content.contentId}/audio.wav`,
      narrationManifest: 'speech/narration-manifest.json',
      narrationMetadata: 'audio/narration-metadata.json',
      requirementsLock: 'requirements.lock.txt',
      tsconfig: 'tsconfig.json',
      remotionConfig: 'remotion.config.ts',
      audioScript: 'scripts/synthesize-audio.mjs',
      audioProducer: 'scripts/synthesize-audio.py',
      renderScript: 'scripts/render-mp4.mjs',
      verifyScript: 'scripts/verify-mp4.mjs',
      qcReport: 'qc/mp4-qc.json',
      renderOutput
    },
    commands: {
      install: 'npm install --ignore-scripts',
      preview: 'npm run preview',
      typecheck: 'npm run typecheck',
      audio: 'npm run audio',
      render: 'npm run render',
      qc: 'npm run qc'
    },
    template: 'a2swe-production-template-v3'
  };
  const visualSections = content.sections.filter((section) => section.visual);
  const usesVisuals = visualSections.length > 0;
  const packageJson = {
    type: 'module', private: true,
    scripts: { preview: 'remotion preview src/index.tsx', audio: 'node scripts/synthesize-audio.mjs', render: 'node scripts/render-mp4.mjs', typecheck: 'tsc --noEmit', qc: 'node scripts/verify-mp4.mjs' },
    dependencies: { '@remotion/cli': '4.0.523', remotion: '4.0.523', react: '19.3.0', 'react-dom': '19.3.0', ...(usesVisuals ? VISUAL_DEPENDENCIES : {}) },
    devDependencies: { '@types/react': '19.3.0', '@types/react-dom': '19.3.0', typescript: '7.0.2' }
  };
  const root = REMOTION_ROOT_TEMPLATE.replaceAll('__THEME_JSON__', JSON.stringify(spec.theme)).replaceAll('__CONTENT_ID__', content.contentId);
  const remotionIndex = `import { registerRoot } from 'remotion';
import { Root } from './Root';

registerRoot(Root);
`;
  // Excalidraw's dependencies ship extensionless ESM imports that webpack rejects by default.
  const remotionConfig = `import { Config } from '@remotion/cli/config';

Config.setOverwriteOutput(true);
Config.setVideoImageFormat('png');
Config.setChromiumOpenGlRenderer('angle');
${usesVisuals ? `Config.overrideWebpackConfig((config) => ({
  ...config,
  module: { ...config.module, rules: [...(config.module?.rules ?? []), { test: /\\.m?js$/, resolve: { fullySpecified: false } }] }
}));
` : ''}`;
  const tsconfig = {
    compilerOptions: {
      target: 'ES2022',
      module: 'ESNext',
      moduleResolution: 'Bundler',
      jsx: 'react-jsx',
      strict: true,
      esModuleInterop: true,
      resolveJsonModule: true,
      isolatedModules: true,
      skipLibCheck: true,
      noEmit: true
    },
    include: ['src/**/*.ts', 'src/**/*.tsx', 'timeline.json', 'remotion.config.ts']
  };
  return [
    { format: 'remotion', path: 'outputs/remotion/render-plan.json', mediaType: 'application/json', bytes: stableJson(plan), adapter: REMOTION_MP4_ADAPTER },
    { format: 'remotion', path: 'outputs/remotion/package.json', mediaType: 'application/json', bytes: stableJson(packageJson), adapter: REMOTION_MP4_ADAPTER },
    { format: 'remotion', path: 'outputs/remotion/requirements.lock.txt', mediaType: 'text/plain', bytes: GENERATED_REQUIREMENTS_LOCK, adapter: REMOTION_MP4_ADAPTER },
    { format: 'remotion', path: 'outputs/remotion/timeline.json', mediaType: 'application/json', bytes: stableJson(timeline), adapter: REMOTION_MP4_ADAPTER },
    { format: 'remotion', path: 'outputs/remotion/asset-manifest.json', mediaType: 'application/json', bytes: stableJson(assetManifest), adapter: REMOTION_MP4_ADAPTER },
    { format: 'remotion', path: 'outputs/remotion/speech/narration-manifest.json', mediaType: 'application/json', bytes: stableJson(narrationManifest), adapter: REMOTION_MP4_ADAPTER },
    ...Array.from(assetMap.values()).filter((asset): asset is ResolvedAsset & { bytes: Buffer; filename: string; mediaType: SupportedImageMediaType } => Boolean(asset.bytes && asset.filename && asset.mediaType))
      .map((asset) => ({ format: 'remotion' as const, path: `outputs/remotion/public/assets/${content.contentId}/${asset.filename}`, mediaType: asset.mediaType, bytes: asset.bytes, adapter: REMOTION_MP4_ADAPTER })),
    { format: 'remotion', path: 'outputs/remotion/tsconfig.json', mediaType: 'application/json', bytes: stableJson(tsconfig), adapter: REMOTION_MP4_ADAPTER },
    { format: 'remotion', path: 'outputs/remotion/remotion.config.ts', mediaType: 'text/typescript', bytes: Buffer.from(remotionConfig), adapter: REMOTION_MP4_ADAPTER },
    { format: 'remotion', path: 'outputs/remotion/scripts/synthesize-audio.mjs', mediaType: 'text/javascript', bytes: Buffer.from(synthesizeAudioWrapperScript()), adapter: REMOTION_MP4_ADAPTER },
    { format: 'remotion', path: 'outputs/remotion/scripts/synthesize-audio.py', mediaType: 'text/x-python', bytes: Buffer.from(synthesizeAudioPython()), adapter: REMOTION_MP4_ADAPTER },
    { format: 'remotion', path: 'outputs/remotion/scripts/render-mp4.mjs', mediaType: 'text/javascript', bytes: Buffer.from(renderScript()), adapter: REMOTION_MP4_ADAPTER },
    { format: 'remotion', path: 'outputs/remotion/scripts/verify-mp4.mjs', mediaType: 'text/javascript', bytes: Buffer.from(verifyScript()), adapter: REMOTION_MP4_ADAPTER },
    { format: 'remotion', path: 'outputs/remotion/src/content.json', mediaType: 'application/json', bytes: stableJson(content), adapter: REMOTION_MP4_ADAPTER },
    { format: 'remotion', path: 'outputs/remotion/src/index.tsx', mediaType: 'text/typescript', bytes: Buffer.from(remotionIndex), adapter: REMOTION_MP4_ADAPTER },
    { format: 'remotion', path: 'outputs/remotion/src/Root.tsx', mediaType: 'text/typescript', bytes: Buffer.from(root), adapter: REMOTION_MP4_ADAPTER },
    { format: 'remotion', path: 'outputs/remotion/src/palette.ts', mediaType: 'text/typescript', bytes: Buffer.from(REMOTION_PALETTE_TEMPLATE.replaceAll('__THEME_JSON__', JSON.stringify(spec.theme))), adapter: REMOTION_MP4_ADAPTER },
    { format: 'remotion', path: 'outputs/remotion/src/Visuals.tsx', mediaType: 'text/typescript', bytes: Buffer.from(usesVisuals ? REMOTION_VISUALS_TEMPLATE : REMOTION_VISUALS_STUB), adapter: REMOTION_MP4_ADAPTER },
    ...visualSections.map((section) => ({ format: 'remotion' as const, path: `outputs/remotion/visuals/${visualStem(content, section.sectionId)}.${VISUAL_EXTENSIONS[section.visual!.kind]}`,
      mediaType: section.visual!.kind === 'marp' ? 'text/markdown' : section.visual!.kind === 'mermaid' ? 'text/plain' : 'application/json',
      bytes: Buffer.from(section.visual!.source.endsWith('\n') ? section.visual!.source : `${section.visual!.source}\n`), adapter: REMOTION_MP4_ADAPTER }))
  ];
}

const EXCALIDRAW_FONT_SOURCE = ['@excalidraw', 'excalidraw', 'dist', 'prod', 'fonts'];

async function prepareRuntime(root: string, content: ContentIR): Promise<() => void> {
  const dependencies = path.join(root, 'node_modules');
  let temporaryDependencies = false;
  const installed = path.join(REPOSITORY_ROOT, 'template', 'node_modules');
  if (!existsSync(dependencies)) {
    const declared = JSON.parse(await readFile(path.join(root, 'package.json'), 'utf8')) as {
      dependencies: Record<string, string>; devDependencies: Record<string, string>;
    };
    for (const [name, version] of Object.entries({ ...declared.dependencies, ...declared.devDependencies })) {
      const installedPackage = path.join(installed, ...name.split('/'), 'package.json');
      if (!existsSync(installedPackage) || JSON.parse(await readFile(installedPackage, 'utf8')).version !== version) {
        throw new Error(`mp4_dependency_unavailable: ${name}@${version}; install generated package dependencies or restore template/node_modules`);
      }
    }
    symlinkSync(installed, dependencies, process.platform === 'win32' ? 'junction' : 'dir');
    temporaryDependencies = true;
  }
  if (content.sections.some((section) => section.visual?.kind === 'excalidraw')) {
    const source = path.join(installed, ...EXCALIDRAW_FONT_SOURCE);
    if (!existsSync(source)) throw new Error('excalidraw_fonts_unavailable: restore template/node_modules');
    // Xiaolai is a 12 MB CJK face; the pipeline is English-only.
    cpSync(source, path.join(root, 'public', 'excalidraw', 'fonts'), { recursive: true, filter: (file) => !file.includes(`${path.sep}Xiaolai`) });
  }
  return () => { if (temporaryDependencies) unlinkSync(dependencies); };
}

function remotionCli(root: string, args: string[], label: string, timeout: number): void {
  const result = spawnSync(process.execPath, [path.join('node_modules', '@remotion', 'cli', 'remotion-cli.js'), ...args], {
    cwd: root, encoding: 'utf8', maxBuffer: 16 * 1024 * 1024, timeout, windowsHide: true
  });
  if (result.error || result.status !== 0) {
    throw new Error(`${label}: ${result.error?.message ?? (result.stderr || result.stdout).trim().slice(0, 4000)}`);
  }
}

// Renders each mermaid, excalidraw or marp section once as a settled PNG so every document format embeds the same image the video shows.
export async function renderVisualStills(releaseRoot: string, content: ContentIR): Promise<AdapterFile[]> {
  const root = path.join(path.resolve(releaseRoot), 'outputs', 'remotion');
  const visuals = content.sections.filter((section) => section.visual);
  if (!visuals.length) return [];
  const cleanup = await prepareRuntime(root, content);
  try {
    for (const section of visuals) {
      const stem = visualStem(content, section.sectionId);
      remotionCli(root, ['still', 'src/index.tsx', `visual-${stem}`, `visuals/${stem}.png`, '--log=error'], `visual_render_failed(${section.sectionId})`, 10 * 60 * 1000);
    }
  } finally { cleanup(); }
  const files: AdapterFile[] = [];
  for (const section of visuals) {
    const relative = `visuals/${visualStem(content, section.sectionId)}.png`;
    const bytes = await readFile(path.join(root, ...relative.split('/')));
    if (bytes.subarray(0, 8).compare(Buffer.from([137, 80, 78, 71, 13, 10, 26, 10])) !== 0) throw new Error(`visual_render_invalid_png: ${section.sectionId}`);
    files.push({ format: 'remotion', path: `outputs/remotion/${relative}`, mediaType: 'image/png', bytes, adapter: REMOTION_MP4_ADAPTER });
  }
  return files;
}

export async function renderEncodedMp4(releaseRoot: string, content: ContentIR): Promise<AdapterFile[]> {
  const contentId = content.contentId;
  const root = path.join(path.resolve(releaseRoot), 'outputs', 'remotion');
  const cleanup = await prepareRuntime(root, content);  try {
    const env = { ...process.env };
    if (!env.A2SWE_PYTHON) {
      const candidate = path.join(REPOSITORY_ROOT, '.venv', process.platform === 'win32' ? 'Scripts' : 'bin',
        process.platform === 'win32' ? 'python.exe' : 'python');
      if (existsSync(candidate)) env.A2SWE_PYTHON = candidate;
    }
    if (env.A2SWE_TTS_ENGINE !== 'kokoro' && env.TTS_ENGINE !== 'kokoro' && (!env.KOKORO_ONNX_MODEL || !env.KOKORO_ONNX_VOICES)) {
      const verification = JSON.parse(await readFile(path.join(REPOSITORY_ROOT, 'qc', 'models', 'verification.json'), 'utf8')) as {
        models: Record<string, string>;
      };
      for (const [suffix, key] of [['.onnx', 'KOKORO_ONNX_MODEL'], ['.bin', 'KOKORO_ONNX_VOICES']] as const) {
        if (env[key]) continue;
        const match = Object.entries(verification.models).find(([filename]) => filename.endsWith(suffix));
        if (!match || !existsSync(match[0])) throw new Error(`mp4_model_unavailable: set ${key} to a local verified ${suffix} model`);
        const hash = createHash('sha256');
        for await (const chunk of createReadStream(match[0])) hash.update(chunk);
        if (hash.digest('hex') !== match[1]) throw new Error(`mp4_model_digest_mismatch: ${match[0]}`);
        env[key] = match[0];
      }
    }
    const result = spawnSync(process.execPath, ['scripts/render-mp4.mjs'], {
      cwd: root, env, encoding: 'utf8', maxBuffer: 16 * 1024 * 1024, timeout: 30 * 60 * 1000, windowsHide: true
    });
    if (result.error || result.status !== 0) {
      throw new Error(`mp4_render_failed: ${result.error?.message ?? (result.stderr || result.stdout).trim().slice(0, 4000)}`);
    }
  } finally { cleanup(); }
  const outputs = [
    ['render-plan.json', 'application/json'],
    ['timeline.json', 'application/json'],
    ['asset-manifest.json', 'application/json'],
    [`public/assets/${contentId}/audio.wav`, 'audio/wav'],
    ['audio/narration-metadata.json', 'application/json'],
    ['dist/render.mp4', 'video/mp4'],
    ['qc/render-receipt.json', 'application/json'],
    ['qc/mp4-qc.json', 'application/json']
  ] as const;
  const files: AdapterFile[] = [];
  for (const [relative, mediaType] of outputs) {
    const bytes = await readFile(path.join(root, ...relative.split('/')));
    if (!bytes.length) throw new Error(`mp4_render_empty_output: ${relative}`);
    files.push({ format: 'remotion', path: `outputs/remotion/${relative}`, mediaType, bytes, adapter: REMOTION_MP4_ADAPTER });
  }
  return files;
}

export function verifyEncodedMp4(releaseRoot: string): void {
  const root = path.join(path.resolve(releaseRoot), 'outputs', 'remotion');
  const result = spawnSync(process.execPath, ['scripts/verify-mp4.mjs', '--verify-only'], {
    cwd: root, encoding: 'utf8', maxBuffer: 16 * 1024 * 1024, timeout: 120000, windowsHide: true
  });
  if (result.error || result.status !== 0) {
    throw new Error(`mp4_qc_failed: ${result.error?.message ?? (result.stderr || result.stdout).trim().slice(0, 4000)}`);
  }
}
