// Generated by scripts/sapi_build.py from script/narration.txt.
export type SubEntry = {from: number; to: number; text: string};
export const SUBS: SubEntry[] = [
  {from: 25, to: 139, text: "Power Platform combines business apps, automation, external sites, and agents."},
  {from: 140, to: 258, text: "Power Apps, Power Automate, Power Pages, and Copilot Studio shape each experience."},
  {from: 269, to: 371, text: "Dataverse provides shared tables, relationships, security, and the solution layer beneath them."},
  {from: 382, to: 489, text: "Production delivery starts with an unmanaged solution and source control as the source of truth."},
  {from: 490, to: 569, text: "Export a managed artifact, then promote it through test and production."},
  {from: 580, to: 731, text: "Resolve target connections and environment variables, while migrating Dataverse records separately because solutions do not carry table data."},
  {from: 742, to: 931, text: "Pipelines simplify promotion; GitHub Actions or Azure DevOps Build Tools support broader automated build, test, package, and deployment workflows."},
  {from: 942, to: 1121, text: "Finish with connector policies, solution checks, end-to-end tests, monitoring, licensing, feature checks, and human approval."},
  {from: 1122, to: 1219, text: "Low code accelerates delivery; engineering responsibility remains."},
];
