// Generated by scripts/sapi_build.py. Frames are 1-based and inclusive.
export const TOTAL_FRAMES = 1264;
export const CHAPTER_STARTS: Array<{n: number; title: string; from: number}> = [
  {n: 1, title: "One platform", from: 25},
  {n: 2, title: "Shared foundation", from: 269},
  {n: 3, title: "Production delivery", from: 382},
  {n: 4, title: "Configuration and data", from: 580},
  {n: 5, title: "CI/CD", from: 742},
  {n: 6, title: "Governed release", from: 942},
];
export type Sentence = {id: string; chapter: number; from: number; to: number; text: string};
export const SENTENCES: Sentence[] = [
  {id: "S01", chapter: 1, from: 25, to: 258, text: "Power Platform combines business apps, automation, external sites, and agents. Power Apps, Power Automate, Power Pages, and Copilot Studio shape each experience."},
  {id: "S02", chapter: 2, from: 269, to: 371, text: "Dataverse provides shared tables, relationships, security, and the solution layer beneath them."},
  {id: "S03", chapter: 3, from: 382, to: 569, text: "Production delivery starts with an unmanaged solution and source control as the source of truth. Export a managed artifact, then promote it through test and production."},
  {id: "S04", chapter: 4, from: 580, to: 731, text: "Resolve target connections and environment variables, while migrating Dataverse records separately because solutions do not carry table data."},
  {id: "S05", chapter: 5, from: 742, to: 931, text: "Pipelines simplify promotion; GitHub Actions or Azure DevOps Build Tools support broader automated build, test, package, and deployment workflows."},
  {id: "S06", chapter: 6, from: 942, to: 1219, text: "Finish with connector policies, solution checks, end-to-end tests, monitoring, licensing, feature checks, and human approval. Low code accelerates delivery; engineering responsibility remains."},
];
