// Generated by scripts/tts_build.py from script/narration.txt.
export type SubEntry = {from: number; to: number; text: string};
export const SUBS: SubEntry[] = [
  {from: 86, to: 156, text: "A field is not one uniform surface."},
  {from: 167, to: 226, text: "John Deere connects positioning,"},
  {from: 227, to: 289, text: "machine displays, and field data"},
  {from: 290, to: 358, text: "to help farmers work more precisely."},
  {from: 369, to: 445, text: "StarFire positioning helps align passes."},
  {from: 456, to: 520, text: "JDLink sends equipment data"},
  {from: 521, to: 571, text: "to Operations Center,"},
  {from: 572, to: 635, text: "where farmers can review performance"},
  {from: 636, to: 681, text: "and plan the next job."},
  {from: 692, to: 763, text: "The point is not just a smarter tractor."},
  {from: 774, to: 831, text: "It is a connected operation,"},
  {from: 832, to: 889, text: "guided by better information."},
];
