// Generated by scripts/tts_build.py. Frames are 1-based and inclusive.
export const TOTAL_FRAMES = 990;
export const CHAPTER_STARTS: Array<{n: number; title: string; from: number}> = [
  {n: 1, title: "Connected farming", from: 86},
];
export type Sentence = {id: string; chapter: number; from: number; to: number; text: string};
export const SENTENCES: Sentence[] = [
  {id: "S01", chapter: 1, from: 86, to: 156, text: "A field is not one uniform surface."},
  {id: "S02", chapter: 1, from: 167, to: 358, text: "John Deere connects positioning, machine displays, and field data to help farmers work more precisely."},
  {id: "S03", chapter: 1, from: 369, to: 445, text: "StarFire positioning helps align passes."},
  {id: "S04", chapter: 1, from: 456, to: 681, text: "JDLink sends equipment data to Operations Center, where farmers can review performance and plan the next job."},
  {id: "S05", chapter: 1, from: 692, to: 763, text: "The point is not just a smarter tractor."},
  {id: "S06", chapter: 1, from: 774, to: 889, text: "It is a connected operation, guided by better information."},
];
