// Generated by scripts/tts_build.py from script/narration.txt.
export type SubEntry = {from: number; to: number; text: string};
export const SUBS: SubEntry[] = [
  {from: 86, to: 166, text: "A field is not one uniform surface."},
  {from: 177, to: 235, text: "John Deere connects positioning,"},
  {from: 236, to: 300, text: "machine displays, and field data"},
  {from: 301, to: 368, text: "to help farmers work more precisely."},
  {from: 379, to: 462, text: "StarFire positioning helps align passes."},
  {from: 473, to: 537, text: "JDLink sends equipment data"},
  {from: 538, to: 584, text: "to Operations Center,"},
  {from: 585, to: 647, text: "where farmers can review performance"},
  {from: 648, to: 690, text: "and plan the next job."},
  {from: 701, to: 778, text: "The point is not just a smarter tractor."},
  {from: 789, to: 845, text: "It is a connected operation,"},
  {from: 846, to: 904, text: "guided by better information."},
];
