"""Generate scene/QC ranges from the narration timeline, not hand-entered frames."""
import argparse
import json
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]


def scene_files(root):
    timeline = json.loads((root / 'script/timeline.json').read_text(encoding='utf-8'))
    chapters = timeline['chapters']
    total = timeline['total_frames']
    if [c['n'] for c in chapters] != list(range(1, 7)):
        raise ValueError('Power Platform requires exactly six ordered chapters')
    starts = [1] + [chapter['from'] for chapter in chapters[1:]]
    ends = [start - 1 for start in starts[1:]] + [total]
    if any(start > end for start, end in zip(starts, ends)):
        raise ValueError('Chapter ranges must increase and cover the full timeline')
    scenes = [{'id': f'SC{i:02d}', 'from': start, 'to': end, 'label': chapter['title']}
              for i, (start, end, chapter) in enumerate(zip(starts, ends, chapters), 1)]
    files = {'src/common/scenes.ts': '// Generated by scripts/sync_scenes.py.\nexport const SCENES = '
             + json.dumps(scenes, indent=2) + ';\n'}
    for i, scene in enumerate(scenes, 1):
        files[f'src/shots/G{i}/index.ts'] = (
            f"export const shots = [{{id: '{scene['id']}', from: {scene['from']}, "
            f"to: {scene['to']}, label: {json.dumps(scene['label'])}}}];\n")
    storyboard = (root / 'storyboard.md').read_text(encoding='utf-8')
    for scene in scenes:
        start, end = scene['from'], scene['to']
        storyboard, count = re.subn(
            rf"^\| {scene['id']} \| [^|]+ \| [^|]+ \|",
            f"| {scene['id']} | {start}-{end} | {(start-1)/30:.1f}-{end/30:.1f}s |",
            storyboard, flags=re.MULTILINE)
        if count != 1:
            raise ValueError(f"Expected one storyboard row for {scene['id']}")
    files['storyboard.md'] = storyboard
    return files


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    for name, content in scene_files(ROOT).items():
        path = ROOT / name
        if args.check:
            if not path.exists() or path.read_text(encoding='utf-8') != content:
                raise SystemExit(f'Stale scene timing: {name}; run npm run audio')
        else:
            path.write_text(content, encoding='utf-8')
    print('Scene, shot registry and storyboard timing match narration.')


if __name__ == '__main__':
    main()
