// Generated by scripts/tts_build.py from script/narration.txt.
export type SubEntry = {from: number; to: number; text: string};
export const SUBS: SubEntry[] = [
  {from: 86, to: 154, text: "An operations agent can answer questions"},
  {from: 155, to: 184, text: "and call tools."},
  {from: 195, to: 242, text: "But who owns it, what can it access,"},
  {from: 243, to: 289, text: "and how do you trace its actions?"},
  {from: 345, to: 451, text: "Microsoft Agent 365 is the control plane"},
  {from: 452, to: 526, text: "for observing, governing, and securing agents."},
  {from: 537, to: 607, text: "It is not the agent builder or runtime."},
  {from: 663, to: 744, text: "Observe: bring inventory and activity into view,"},
  {from: 745, to: 821, text: "then trace agent invocations and tool calls."},
  {from: 877, to: 941, text: "Govern: establish ownership, identities,"},
  {from: 942, to: 1001, text: "permissions, and lifecycle controls."},
  {from: 1057, to: 1131, text: "Secure: connect identity, data protection,"},
  {from: 1132, to: 1178, text: "and threat detection through Entra,"},
  {from: 1179, to: 1215, text: "Purview, and Defender."},
  {from: 1271, to: 1337, text: "When code-level integration is needed,"},
  {from: 1338, to: 1421, text: "add only the SDK capabilities required."},
  {from: 1432, to: 1498, text: "Keep your existing framework and hosting."},
  {from: 1554, to: 1613, text: "Start with one accountable pilot."},
  {from: 1624, to: 1696, text: "Verify licensing and preview limitations,"},
  {from: 1697, to: 1778, text: "test the controls, then expand with evidence."},
];
