// Generated by scripts/tts_build.py. Frames are 1-based and inclusive.
export const TOTAL_FRAMES = 1879;
export const CHAPTER_STARTS: Array<{n: number; title: string; from: number}> = [
  {n: 1, title: "One agent. Three questions.", from: 86},
  {n: 2, title: "The control plane", from: 345},
  {n: 3, title: "Observe", from: 663},
  {n: 4, title: "Govern", from: 877},
  {n: 5, title: "Secure", from: 1057},
  {n: 6, title: "Extend what you built", from: 1271},
  {n: 7, title: "Start with evidence", from: 1554},
];
export type Sentence = {id: string; chapter: number; from: number; to: number; text: string};
export const SENTENCES: Sentence[] = [
  {id: "S01", chapter: 1, from: 86, to: 184, text: "An operations agent can answer questions and call tools."},
  {id: "S02", chapter: 1, from: 195, to: 289, text: "But who owns it, what can it access, and how do you trace its actions?"},
  {id: "S03", chapter: 2, from: 345, to: 526, text: "Microsoft Agent 365 is the control plane for observing, governing, and securing agents."},
  {id: "S04", chapter: 2, from: 537, to: 607, text: "It is not the agent builder or runtime."},
  {id: "S05", chapter: 3, from: 663, to: 821, text: "Observe: bring inventory and activity into view, then trace agent invocations and tool calls."},
  {id: "S06", chapter: 4, from: 877, to: 1001, text: "Govern: establish ownership, identities, permissions, and lifecycle controls."},
  {id: "S07", chapter: 5, from: 1057, to: 1215, text: "Secure: connect identity, data protection, and threat detection through Entra, Purview, and Defender."},
  {id: "S08", chapter: 6, from: 1271, to: 1421, text: "When code-level integration is needed, add only the SDK capabilities required."},
  {id: "S09", chapter: 6, from: 1432, to: 1498, text: "Keep your existing framework and hosting."},
  {id: "S10", chapter: 7, from: 1554, to: 1613, text: "Start with one accountable pilot."},
  {id: "S11", chapter: 7, from: 1624, to: 1778, text: "Verify licensing and preview limitations, test the controls, then expand with evidence."},
];
