// Generated by scripts/tts_build.py from script/narration.txt.
export type SubEntry = {from: number; to: number; text: string};
export const SUBS: SubEntry[] = [
  {from: 31, to: 95, text: "A field is not one uniform surface."},
  {from: 100, to: 156, text: "John Deere connects positioning,"},
  {from: 157, to: 214, text: "machine displays, and field data"},
  {from: 215, to: 278, text: "to help farmers work more precisely."},
  {from: 283, to: 355, text: "StarFire positioning helps align passes."},
  {from: 360, to: 412, text: "JDLink sends equipment data"},
  {from: 413, to: 458, text: "to Operations Center,"},
  {from: 459, to: 519, text: "where farmers can review performance"},
  {from: 520, to: 564, text: "and plan the next job."},
  {from: 569, to: 630, text: "The point is not just a smarter tractor."},
  {from: 635, to: 683, text: "It is a connected operation,"},
  {from: 684, to: 732, text: "guided by better information."},
];
